# -*- coding: utf-8 -*-
import json, os, copy
ROOT="G:/workbuddy/2026-06-28-23-34-20/silver-pulse"
PATH=os.path.join(ROOT,"data/enterprise/all_enterprises.json")
data=json.load(open(PATH,encoding="utf-8"))
by={e["serial"]:e for e in data}

# 主智能体亲自定的分（signal/info/diff/copy 已按文档1阶段3+阶段4证据核算）
# research_value = round((sig*0.3 + info*0.3 + diff*0.2 + copy*0.2)*10)
U={
"#0470": dict(founded="2014",
  desc_cn="美国数字肌肉骨骼(MSK)疼痛护理龙头，纽交所上市公司(代码HNGE，2025-05 IPO)。通过AI动作追踪+FDA认证可穿戴设备Enso+健康教练，为自保雇主与健康计划提供虚拟与面对面结合的慢病疼痛/术后康复护理，以降低手术率与医疗成本；2024财年营收约3.9亿美元，已接近盈利。",
  payor_model="B端机构付费（雇主与健康计划采购MSK福利，会员零自付）+ 正拓展Medicare Advantage",
  funding_latest={"round":"IPO","amount":"4.373亿美元","currency":"USD","date":"2025-05","display":"IPO 募资4.373亿美元 (2025-05)","investors":["NYSE公开发行(HNGE)"]},
  funding_total={"amount":"约12.9亿美元(含IPO)","display":"累计约12.9亿美元(含IPO)"},
  investors=["NYSE公开发行(HNGE)"],
  highlights=["纽交所上市 HNGE（2025-05）","AI动作追踪+FDA认证可穿戴Enso镇痛","服务自保雇主与健康计划，目标降低手术率"],
  signal_strength=6.8,info_score=9,diff_score=4,copy_score=5,
  recommend="数字肌肉骨骼护理信息密度极高（上市公司财报+WSJ/Bloomberg密集报道），研究素材充足；但商业模式本身顺常识、IPO为down-round，差异化与反共识性偏弱。对中国的启发在支付方：它靠自保雇主采购MSK福利、会员零自付跑通，而国内同类（术康、卓道）仍依赖医院/医保，雇主健康福利付费意愿弱——这套“雇主福利+降手术率”的付费闭环才是真正值得拆解的切入点。"),
"#0866": dict(founded="2016",
  desc_cn="AI驱动的“精准心理健康”福利平台，为雇主与健康计划提供员工心理筛查、智能分诊与最佳治疗匹配（咨询/药物/教练），以临床效果与ROI为核心卖点；2024年完成1亿美元E轮、估值33亿美元，覆盖超1000万生命、400+直签雇主（微软/Target/JPMorgan等）。",
  payor_model="B端机构付费（雇主与健康计划订阅采购，员工免费使用）",
  funding_latest={"round":"E轮","amount":"1亿美元","currency":"USD","date":"2024-07","display":"E轮 1亿美元 (2024-07)","investors":["Generation Investment Management","Kinnevik","Northzone","RRE Ventures"]},
  funding_total={"amount":"约4.7亿美元","display":"累计约4.7亿美元"},
  investors=["Generation Investment Management","Kinnevik","Northzone","RRE Ventures"],
  highlights=["精准心理健康匹配平台，覆盖超1000万生命","E轮1亿美元、估值33亿美元(2024-07)","客户含微软/Target/JPMorgan等400+雇主"],
  signal_strength=4.55,info_score=9,diff_score=3,copy_score=5,
  recommend="心理健康福利信息丰富（公司新闻稿+Fortune+Fierce透明），但模式顺常识、估值稳健上行，反共识性低。中国已有简单心理、壹心理、好心情等，但支付以C端自费/医院为主、企业EAP采购规模小——真正可借鉴的是它用ROI(2.2x回报)量化心理福利、绑定雇主采购的打法，而非产品本身。"),
"#0886": dict(founded="2020",
  desc_cn="面向自保雇主与健康计划的AI驱动医疗福利与就医导航平台（WayFinding生成式AI导诊），整合癌症/手术/减重/药房福利与虚拟问诊；由Livongo创始人Glen Tullman创立，2025年以6.21亿美元收购Accolade补足健康倡导与初级护理。",
  payor_model="B端机构付费（自保雇主与健康计划付费；收入与为雇主节省的医疗成本绑定）",
  funding_latest={"round":"D轮","amount":"1.26亿美元","currency":"USD","date":"2024-05","display":"D轮 1.26亿美元 (2024-05)","investors":["General Catalyst","7wire Ventures","Kinnevik","Kleiner Perkins","Merck GHIF"]},
  funding_total={"amount":"约4.2亿美元","display":"累计约4.2亿美元(估值22亿美元)"},
  investors=["General Catalyst","7wire Ventures","Kinnevik","Kleiner Perkins","Merck GHIF"],
  highlights=["Livongo创始人Glen Tullman创立","WayFinding生成式AI导诊","2025以6.21亿美元收购Accolade"],
  signal_strength=4.55,info_score=8,diff_score=7,copy_score=4,
  recommend="信息量中高（多起M&A+创始团队光环），差异化强在“收入与雇主省下的医疗费挂钩”这一绑定模式，连续并购扩张估值22亿美元。中国类似有健康险TPA、就医导航（思派、镁信），但美国自保雇主体系独特、支付以雇主直付为主，国内以社保+商保，平移需重构支付方——重点拆解其“省钱才赚钱”的激励设计。"),
"#0974": dict(founded="2014",
  desc_cn="消费级AI智能睡眠硬件公司，核心产品Pod智能床垫罩（水循环温控+生物传感监测心率/呼吸/HRV），用Autopilot/Sleep Agent实时调节睡眠环境；硬件+会员订阅模式，2025-08完成1亿美元D轮，2026-03获Tether 5000万美元、估值15亿美元，2026-04进入中国。",
  payor_model="个人自付(C端)：硬件销售+Autopilot会员订阅；2026入华取消订阅费改DTC电商",
  funding_latest={"round":"战略轮","amount":"5000万美元","currency":"USD","date":"2026-03","display":"战略轮 5000万美元 (2026-03, Tether领投)","investors":["Tether Investments","Khosla Ventures","Founders Fund","HSG","Y Combinator"]},
  funding_total={"amount":"约3.1亿美元","display":"累计约3.1亿美元(估值15亿美元)"},
  investors=["Tether Investments","Khosla Ventures","Founders Fund","HSG","Y Combinator"],
  highlights=["Pod智能床垫罩(温控+生物监测)","硬件+强制会员订阅模式","2026-04进入中国，取消订阅改DTC"],
  signal_strength=4.8,info_score=8,diff_score=4,copy_score=5,
  recommend="消费硬件明星信息丰富（科技媒体+融资库），但“床垫需订阅”有争议、估值稳步上行，反共识性一般。中国睡眠/智能床赛道拥挤（麒盛、梦百合、ChiliSleep），高价+订阅DTC+AI是差异点；入华已取消订阅改电商，本土化挑战大——可观察其“硬件+数据订阅”能否在中国跑通。"),
"#0853": dict(founded="2018",
  desc_cn="直接面向雇主的透明定价健康险运营商（ACA合规重大医疗险），会员持Sidecar Health Visa福利卡按协商价直接向诊所付费，无网络限制、无事先授权；2021年成独角兽，2024-06完成1.65亿美元D轮，覆盖44+州。",
  payor_model="商业保险/雇主福利(B端)：雇主赞助保险，会员用Visa福利卡直付并按节省分润",
  funding_latest={"round":"D轮","amount":"1.65亿美元","currency":"USD","date":"2024-06","display":"D轮 1.65亿美元 (2024-06)","investors":["Koch Disruptive Technologies","GreatPoint Ventures","BOND Capital","Menlo Ventures","Drive Capital"]},
  funding_total={"amount":"约3亿美元","display":"累计约3亿美元(独角兽)"},
  investors=["Koch Disruptive Technologies","GreatPoint Ventures","BOND Capital","Menlo Ventures","Drive Capital"],
  highlights=["透明定价+无网络限制健康险","Visa福利卡直付、会员按节省分润","2021成独角兽，覆盖44+州"],
  signal_strength=4.55,info_score=7,diff_score=8,copy_score=3,
  recommend="信息量中高（保险科技媒体+融资库），差异化极强：“去网络、透明定价、会员按节省分润”颠覆传统HMO/PPO，但规模化挑战大。中国商业健康险以社保补充+百万医疗险为主，缺乏“无网络透明直付+会员分润”模式、雇主直付福利不成熟，支付方结构差异极大，直接平移难度高——其“透明定价+分润”机制本身值得借鉴。"),
"#0964": dict(founded="2012",
  desc_cn="开发非手术（血管内）脑机接口Stentrode，经颈静脉微创植入运动皮层，帮助瘫痪患者用思维控制数字设备（iPad/Vision Pro/Alexa）；2025-08全球首例通过Apple BCI协议用意念控制iPad（ALS患者），2025-11完成2亿美元D轮。",
  payor_model="B端机构付费（面向医院/医疗系统的植入式设备；远期或由商业/政府医疗保险覆盖，尚未商业上市）",
  funding_latest={"round":"D轮","amount":"2亿美元","currency":"USD","date":"2025-11","display":"D轮 2亿美元 (2025-11)","investors":["Double Point Ventures","ARCH Ventures","Khosla Ventures","Bezos Expeditions","QIA"]},
  funding_total={"amount":"约3.45亿美元","display":"累计约3.45亿美元"},
  investors=["Double Point Ventures","ARCH Ventures","Khosla Ventures","Bezos Expedations","QIA"],
  highlights=["血管内微创脑机接口Stentrode(免开颅)","2025首例意念控制iPad(ALS患者)","D轮2亿美元(2025-11)"],
  signal_strength=5.3,info_score=9,diff_score=9,copy_score=4,
  recommend="信息量极高（Bloomberg/Forbes/Wired/TIME密集报道+临床植入数据），差异化极强：免开颅血管内脑机接口是前沿稀缺路线。中国强脑科技(BrainCo)、博睿康等同赛道，但微创血管内路线稀缺、监管与支付路径未定，难直接平移——值得作为“脑机接口临床转化+支付方演进”的硬核案例。"),
"#0872": dict(founded="2018",
  desc_cn="美国价值导向(value-based)肾脏护理全国领导者，用AI+现场护理团队为CKD→ESKD全旅程患者提供早期干预，按价值医疗合同向健康计划与医疗系统收费；2025-09完成5.5亿美元D轮（3亿股权+2.5亿债务），估值18亿美元，管理近50亿美元年医疗支出、服务14.5万+患者。",
  payor_model="混合（商业保险+政府Medicare/MA，通过风险/价值医疗合同向健康计划与医疗系统收费）",
  funding_latest={"round":"D轮","amount":"5.5亿美元(3亿股权+2.5亿债务)","currency":"USD","date":"2025-09","display":"D轮 5.5亿美元 (2025-09)","investors":["NEA","CVS Health Ventures","CapitalG","Echo Health Ventures","Redpoint"]},
  funding_total={"amount":"约7亿美元","display":"累计约7亿美元"},
  investors=["NEA","CVS Health Ventures","CapitalG","Echo Health Ventures","Redpoint"],
  highlights=["价值导向肾脏护理全国龙头","D轮5.5亿美元(2025-09)，估值18亿","管理近50亿美元年医疗支出、14.5万+患者"],
  signal_strength=4.8,info_score=8,diff_score=4,copy_score=4,
  recommend="信息丰富（财务与临床成效披露充分：降本20%、住院降41%），但VBC肾脏护理模式稳健、规模化扩张无剧烈起落，反共识性低。中国肾病慢病管理（智云健康、京东健康）有同类，但按价值付费(VBC)的支付环境差异大、风险承担机制缺失，难直接平移——重点看其“风险分层+现场护理”如何绑定支付方分成。"),
"#0861": dict(founded="2016",
  desc_cn="价值导向肾脏与心血管综合护理龙头，与健康计划、医疗系统、医生集团合作，以本地多学科团队+预测分析(RenalIQ)延缓疾病进展、降低总医疗成本；2025-06完成约7500万美元G轮、估值约49.8亿美元，服务突破50万生命。",
  payor_model="混合（健康计划+政府Medicare价值医疗合同，B端机构付费为主）",
  funding_latest={"round":"G轮","amount":"约7500万美元","currency":"USD","date":"2025-06","display":"G轮 约7500万美元 (2025-06)","investors":["未披露(Forge标注Undisclosed)"]},
  funding_total={"amount":"约14亿美元(含可转债)","display":"累计约14亿美元(含可转债结构)"},
  investors=["未披露"],
  highlights=["价值导向肾+心血管综合护理龙头","G轮约7500万美元(2025-06)，估值约49.8亿","服务突破50万生命，降低肾病死亡率13%"],
  signal_strength=3.8,info_score=7,diff_score=4,copy_score=4,
  recommend="信息中等（Forge有详细融资与估值，临床成效有第三方研究），VBC模式稳健、扩张平稳，反共识性低。与Strive同赛道，中国肾病管理玩家众多但按价值付费环境差异大——两家并列看，可对比“纯肾护理”与“肾+多专科”两种VBC扩张路径的异同。"),
"#0977": dict(founded="2014",
  desc_cn="用行为经济学+财务激励做“每日护理激励”的数字健康公司，提升高风险人群（Medicare Advantage/Medicaid/D-SNP）用药依从与预防就诊；2025-03完成3600万美元超额认购C轮，累计5000万+次每日打卡、平均90%护理计划依从、住院降51%。",
  payor_model="混合（客户为健康计划，终极支付方为政府Medicare/Medicaid；B端机构付费+政府支付主导）",
  funding_latest={"round":"C轮","amount":"3600万美元","currency":"USD","date":"2025-03","display":"C轮 3600万美元 (2025-03)","investors":["Mercato Partners","FCA Venture Partners","Comcast Ventures","SignalFire","New York Life"]},
  funding_total={"amount":"约7310万美元","display":"累计约7310万美元"},
  investors=["Mercato Partners","FCA Venture Partners","Comcast Ventures","SignalFire","New York Life"],
  highlights=["行为经济学+每日财务激励提升依从","C轮3600万美元(2025-03)","累计5000万+次打卡，住院降51%"],
  signal_strength=2.55,info_score=8,diff_score=6,copy_score=5,
  recommend="信息丰富（临床与财务成效指标清晰），差异化在“行为经济学+每日小额激励”提升慢病依从、降低住院，模式有一定独特性。中国慢病管理（平安好医生、微医）有同类，但按效果付费+政府支付方结构差异大——其“用微小金钱激励撬动依从率”的行为设计值得借鉴，尤其适配国内医保控费语境。"),
"#0392": dict(founded="2015",
  desc_cn="上海康复机器人公司，两大板块：康复机器人（外骨骼、上下肢康复）与通用人形机器人（GR系列），具身智能赋能康养场景；2025-01完成近8亿元E轮（史上最大单笔，国鑫投资领投），产品进入60+国、3000+机构。",
  payor_model="混合（康复机器人以B端医疗机构/康复中心采购为主，C端辅助器具含个人自付；人形机器人面向企业场景）",
  funding_latest={"round":"E轮","amount":"近8亿元","currency":"CNY","date":"2025-01","display":"E轮 近8亿元 (2025-01)","investors":["国鑫投资","浦东创投","张江科投","Prosperity7 Ventures","钧山资本"]},
  funding_total={"amount":"约15亿元+","display":"累计约15亿元+(含D+E轮)"},
  investors=["国鑫投资","浦东创投","张江科投","Prosperity7 Ventures","钧山资本"],
  highlights=["康复机器人+通用人形机器人双板块","E轮近8亿元(2025-01)，史上最大单笔","产品进入60+国、3000+机构"],
  signal_strength=5.55,info_score=9,diff_score=8,copy_score=8,
  recommend="国内公开信息极丰富（华夏时报、21世纪、证券时报密集报道），差异化强在从康复跨界人形机器人、估值随风口大起大落，反共识风险高。中国康复机器人赛道拥挤（大艾、程天）技术同源可平移、人形机器人商业化尚早——这是少有的“国内标杆+强借鉴”样本：既看技术路线，也看资本如何押注具身智能康养。"),
"#0895": dict(founded="2011",
  desc_cn="4D成像雷达(radar-on-chip)公司，以无摄像头、隐私保护的非接触式环境感知服务养老跌倒监测、智能家居、汽车与医疗等多场景；2024-10完成2500万美元扩展轮，累计约3.23亿美元，2020年在中国成立全资子公司并建研发中心。",
  payor_model="B端机构付费（向OEM、养老机构与智能家居厂商出售雷达芯片/模组与方案，不直接对个人）",
  funding_latest={"round":"E轮扩展轮","amount":"2500万美元","currency":"USD","date":"2024-10","display":"E轮扩展轮 2500万美元 (2024-10)","investors":["ITI Venture Capital Partners"]},
  funding_total={"amount":"约3.23亿美元","display":"累计约3.23亿美元"},
  investors=["ITI Venture Capital Partners"],
  highlights=["4D成像雷达(无摄像头、隐私保护)","Vayyar Care养老跌倒监测方案","2020在华设全资子公司+研发中心"],
  signal_strength=2.55,info_score=8,diff_score=5,copy_score=7,
  recommend="信息较丰富（官网+CB Insights+中文创业媒体），商业模式合理（卖传感器给厂商）不反常识。中国有同类毫米波雷达（清雷、移远），但Vayyar全自研RFIC+多天线阵列壁垒高；支付方为B端，其“雷达替代摄像头做跌倒监测”可直接平移至国内养老机构与智能家居厂商——是技术引进+本土集成的好样本。"),
"#0969": dict(founded="2023",
  desc_cn="专注“安全第一”的医疗生成式AI代理公司，提供不诊断、不开方的低风险面向患者AI客服（随访、预约、用药/筛查提醒）；2025-11完成1.26亿美元C轮、估值35亿美元，与50+大型医疗系统/支付方/药企合作，累计超1.15亿次临床患者互动。",
  payor_model="B端机构付费（向医疗系统、健康计划/支付方、药企收SaaS/使用费）",
  funding_latest={"round":"C轮","amount":"1.26亿美元","currency":"USD","date":"2025-11","display":"C轮 1.26亿美元 (2025-11)","investors":["Avenir Growth","CapitalG","General Catalyst","a16z","Kleiner Perkins","Premji Invest"]},
  funding_total={"amount":"约4.04亿美元","display":"累计约4.04亿美元(估值35亿)"},
  investors=["Avenir Growth","CapitalG","General Catalyst","a16z","Kleiner Perkins","Premji Invest"],
  highlights=["安全优先的医疗生成式AI代理(不诊断)","C轮1.26亿美元(2025-11)，估值35亿","合作50+医疗系统/支付方，1.15亿+次互动"],
  signal_strength=5.3,info_score=9,diff_score=6,copy_score=6,
  recommend="信息非常丰富（官网新闻中心+Reuters+Yahoo），模式清晰不反常识但增长极快（15个月商业化、千余用例）。中国有医疗大模型客服/随访玩家，但“安全优先+无诊断”定位与美国payor/provider支付方差异大——其“低风险AI代理替代人力客服”的合规边界设计与商业化速度值得重点拆解。"),
"#0618": dict(founded="1982",
  desc_cn="长期照护/后急性期(post-acute)领域的电子健康记录(EHR)与营收周期管理(RCM)软件商；2024-01被PointClickCare收购并并入其产品组合。",
  payor_model="B端机构付费（向养老院/SNF/辅助生活机构出售EHR SaaS）",
  funding_latest={"round":"被收购","amount":"未披露","currency":"USD","date":"2024-01","display":"被PointClickCare收购 (2024-01)","investors":["PointClickCare(买方)"]},
  funding_total={"amount":"未披露","display":"被并购，无独立累计融资披露"},
  investors=["PointClickCare"],
  highlights=["长期照护EHR+RCM老牌厂商","2024-01被PointClickCare收购","传统EHR行业整合案例"],
  signal_strength=0.55,info_score=6,diff_score=3,copy_score=8,
  recommend="信息中等（收购新闻+PitchBook档案），传统EHR软件商、模式稳健不反常识。中国有大量养老院/护理院HIS/EHR厂商，业务高度可平移、支付方同为机构采购——这家本身故事性弱，但作为“美国养老IT被整合”的背景注脚有用，可类比国内嘉和美康等。"),
"#0944": dict(founded="1974",
  desc_cn="个人紧急响应系统(PERS)先驱品牌，提供可穿戴紧急呼叫按钮+24/7紧急响应中心服务；1974年成立，2006年被飞利浦收购，2021年转手Connect America（飞利浦保留股权）。",
  payor_model="个人自付为主（月付订阅约30-50美元）+ 部分经医院/养老机构渠道推荐（混合）",
  funding_latest={"round":"被收购","amount":"未披露","currency":"USD","date":"2021-07","display":"被Connect America收购 (2021-07)","investors":["Connect America(买方)","飞利浦保留股权"]},
  funding_total={"amount":"不适用","display":"品牌/部门，已被并购"},
  investors=["Connect America","飞利浦"],
  highlights=["PERS紧急响应系统先驱(1974)","AutoAlert自动跌倒检测","2006飞利浦收购→2021转手Connect America"],
  signal_strength=0.55,info_score=6,diff_score=3,copy_score=8,
  recommend="信息中等（品牌历史清晰，但作为飞利浦部门财务不独立），近50年持续运营、模式成熟不反常识。中国PERS/一键呼叫/跌倒报警玩家众多（小米、华为、平安），业务可平移、支付方以个人自付+长护险/政府补贴为主——可作为“老牌PERS如何迭代到跌倒检测+订阅”的对照样本。"),
"#1152": dict(founded="1970",
  desc_cn="全球最大医疗地产信托(REIT，纽交所WELL)，持有并运营养老社区(SHOP)、医疗办公楼、门诊与长期急症护理地产，是美国“银发地产”定价锚；2025-10宣布230亿美元交易组合（约140亿收购养老社区），2026 Q1完成41笔交易共32亿美元。",
  payor_model="B端机构付费为主（向养老运营商收租/分成；终端需求来自入住长者，WELL直接收费对象为运营商）",
  funding_latest={"round":"重大交易/资本运作","amount":"230亿美元(约140亿为收购)","currency":"USD","date":"2025-10","display":"230亿美元交易组合 (2025-10，含约140亿收购)","investors":["公共股权/债务市场","ADIA等第三方LP"]},
  funding_total={"amount":"不适用","display":"上市REIT，2025市值约1490亿美元"},
  investors=["公共市场"],
  highlights=["全球最大医疗地产REIT(纽交所WELL)","2025-10宣布230亿美元交易组合","SHOP入住率87.3%(2026 Q1)"],
  signal_strength=7.3,info_score=10,diff_score=3,copy_score=7,
  recommend="信息极丰富（上市公司财报+投资者关系+行业媒体全覆盖），REIT收租模式成熟不反共识，但2025激进加仓养老社区、股价年内涨约49%。中国无纯养老REIT上市品种，但险资/养老地产基金（平安、泰康）可对标其资产组合、出租率与“Right Market/Asset/Operator”逻辑——是理解“银发地产资本闭环”的必读标杆。"),
"#1153": dict(founded="1983",
  desc_cn="美国第二大养老/医疗地产REIT（纽交所VTR），持有并运营养老社区、门诊医疗与研究院、长期急症护理地产；1998年上市，2025年通过远期股权协议结算约1640万股、募资约11亿美元用于养老社区投资。",
  payor_model="B端机构付费（Triple-net净租赁，运营商付租金；终端来自政府医保Medicare/Medicaid+个人自付）",
  funding_latest={"round":"上市公司/远期股权增发","amount":"约11亿美元","currency":"USD","date":"2025","display":"2025远期股权增发约11亿美元","investors":["公共市场"]},
  funding_total={"amount":"不适用","display":"持续公开市场融资，企业价值约500亿美元"},
  investors=["公共市场"],
  highlights=["美国第二大养老/医疗REIT(纽交所VTR)","2025增发约11亿美元加仓养老社区","SHOP同店现金NOI同比+13%(2025 Q2)"],
  signal_strength=6.3,info_score=9,diff_score=3,copy_score=7,
  recommend="信息极丰富（官网IR+Q2 2025财报+1400+处物业数据），REIT模式稳健、受老龄化与新建供给低位双重顺风，起伏平缓。中国无直接上市养老REIT，但险资/养老地产基金可对标其资产组合与出租率逻辑——与Welltower并读，能看清“银发地产”这门生意的资本纪律与周期。"),
"#1169": dict(founded="2001",
  desc_cn="欧洲依赖人群照护设施领先私营运营商（泛欧证交所CLAR，原Korian），覆盖长期照护、专科护理与社区照护；2023年6月更名Clariane并获“使命驱动型公司”地位，2024年营收约52.82亿欧元、服务88.6万人。",
  payor_model="混合（欧洲养老院费用主要由政府社会医保/地方财政报销+居民个人自付补足；高端房间与增值服务以个人自付为主）",
  funding_latest={"round":"上市公司/混合票据","amount":"3.33亿欧元","currency":"EUR","date":"2026-06","display":"拟发行3.33亿欧元永续混合票据 (2026-06)","investors":["公共市场"]},
  funding_total={"amount":"不适用","display":"持续公开市场+债务融资，房地产组合约26亿欧元"},
  investors=["公共市场"],
  highlights=["欧洲养老运营龙头(原Korian)","2024营收52.82亿欧元，服务88.6万人","2023更名Clariane，获使命驱动型地位"],
  signal_strength=5.3,info_score=8,diff_score=3,copy_score=7,
  recommend="信息丰富（2024年报+投资者区完整），欧洲规模化养老运营龙头、财务结构重组后趋稳，非剧烈起落。中国连锁养老运营商（泰康之家、亲和源、九如城）可对标其规模化+多国本土化，但支付以个人/医保为主、政府补贴结构不同——看欧洲“政府报销+个人补足”如何支撑重资产运营，对国内定价有参考。"),
"#0493": dict(founded="1966",
  desc_cn="全球最大消费电子零售商（纽交所BBY），通过Best Buy Health进军老年科技与居家照护，核心品牌Lively与PERS+紧急响应；2018年8亿美元收购GreatCall、2021年约4亿美元收购Current Health，但2025年6月将Current Health回售原团队并累计计提健康业务商誉减值超6亿美元。",
  payor_model="混合（Lively/PERS+以个人自付为主；亦B端与医疗系统/支付方合作居家照护项目）",
  funding_latest={"round":"上市公司/收购支出","amount":"约4亿美元(收购Current Health,2021)","currency":"USD","date":"2021-10","display":"收购Current Health约4亿美元 (2021-10)","investors":["Best Buy(买方)"]},
  funding_total={"amount":"不适用","display":"上市公司，自身无融资轮"},
  investors=["Best Buy"],
  highlights=["零售巨头跨界老年科技(Best Buy Health)","2021收购Current Health，2025回售并减值超6亿","典型“零售+临床”模式错配反例"],
  signal_strength=4.55,info_score=8,diff_score=8,copy_score=7,
  recommend="信息丰富（上市公司财报+多次收购/剥离详尽），是少有的反共识案例：零售巨头跨界老年科技后战略收缩、累计减值超6亿美元，验证了零售+临床医疗的模式错配风险。中国零售/家电巨头（京东健康、苏宁）可参考其“收购试错+剥离止损”路径——这比成功案例更能帮国内创业者避坑。"),
"#1155": dict(founded="1992",
  desc_cn="专注专业护理院(SNF)与辅助生活(ALF)的医疗REIT（纽交所OHI），以Triple-net净租赁为美国护理院地产最大持有人之一；2025年末投资资产115亿美元、1111处物业、9.3万+张床位，2025年新设20亿美元ATM计划。",
  payor_model="B端机构付费（Triple-net净租赁，运营商付租金；终端护理报销来自政府Medicare/Medicaid为主+个人自付）",
  funding_latest={"round":"上市公司/公开增发","amount":"约2.22亿美元","currency":"USD","date":"2025-Q4","display":"2025 Q4发行Omega OP Units约2.22亿美元","investors":["公共市场"]},
  funding_total={"amount":"不适用","display":"持续公开市场+债务融资，总资产约115亿美元"},
  investors=["公共市场"],
  highlights=["专业护理院REIT龙头(纽交所OHI)","2025投资资产115亿美元、1111处物业","2025 Genesis破产凸显租户集中度风险"],
  signal_strength=5.3,info_score=8,diff_score=4,copy_score=5,
  recommend="信息丰富（2025年报+FAQ+组合数据），纯护理院Triple-net REIT模式稳健但高度依赖运营商偿付能力（2025年租户Genesis破产凸显集中度风险），非剧烈起落。国内护理院重资产持有可参考triple-net结构，但中国REITs/ABS市场与医保支付差异大，纯SNF REIT难直接平移——其“租户风险管控”是核心看点。"),
"#1156": dict(founded="2014",
  desc_cn="专注养老社区与医疗地产的自管理REIT（NASDAQ:CTRE），以低杠杆+Triple-net净租赁+高出租率著称；2014年自The Ensign Group分拆上市，2025年以约8.17亿美元收购英国Care REIT（135处物业）开启出海，连续10年提高股息。",
  payor_model="B端机构付费（Triple-net净租赁，运营商付租金；终端来自政府Medicare/Medicaid+个人自付）",
  funding_latest={"round":"上市公司/公开增发","amount":"7.36亿美元","currency":"USD","date":"2025-Q3","display":"2025 Q3公开募资7.36亿美元","investors":["公共市场"]},
  funding_total={"amount":"不适用","display":"持续公开市场融资，市值约95亿美元"},
  investors=["公共市场"],
  highlights=["自管理养老REIT(NASDAQ:CTRE)","2025收购英国Care REIT出海","连续10年提高股息"],
  signal_strength=5.3,info_score=8,diff_score=4,copy_score=6,
  recommend="信息丰富（年报+投资者演示+英国收购报道），从单租户分拆到多元化+出海的成长型REIT，模式清晰非反共识。国内“运营+地产”分拆REIT可参考其资本架构；但A股无纯养老REIT、出海逻辑难复制——其“轻杠杆+高出租率+多元租户”的资本纪律值得借鉴。"),
"#1170": dict(founded="2001",
  desc_cn="欧洲依赖人群照护运营商（原Orpea，泛欧证交所），曾因财务造假与照护质量丑闻陷入危机，后重组转型；2024年营收持平、推进资产出售与杠杆去化。",
  payor_model="混合（欧洲养老院费用政府社会医保报销+居民个人自付补足）",
  funding_latest={"round":"上市公司/债务重组","amount":"财务重组中","currency":"EUR","date":"2024","display":"上市公司，2024推进债务重组与资产出售","investors":["公共市场"]},
  funding_total={"amount":"不适用","display":"持续公开市场+债务融资"},
  investors=["公共市场"],
  highlights=["原Orpea，欧洲养老运营巨头","曾陷财务造假与照护质量丑闻","重组转型、去杠杆中"],
  signal_strength=0.55,info_score=7,diff_score=5,copy_score=6,
  recommend="信息中等（欧洲财经媒体+年报），是罕见的“暴雷—重组”反共识样本：从造假丑闻到债务重组，起落极大。中国连锁养老运营商可对照其治理教训——规模化的同时如何避免“重资产+预收费+治理失效”的爆雷路径，比成功学更有警示价值。"),
"#1158": dict(founded="1992",
  desc_cn="美国最大独立居家输液(infusion)与专业药物管理服务商（NASDAQ:OPCH），为复杂慢病（免疫、肿瘤、罕见病）患者提供居家/门诊输液；1984年成立，通过并购成长为赛道龙头。",
  payor_model="混合（医保/商业保险报销为主，个人自付为辅；B端机构合作）",
  funding_latest={"round":"上市公司","amount":"不适用","currency":"USD","date":"1984","display":"上市公司(NASDAQ:OPCH)","investors":["公共市场"]},
  funding_total={"amount":"不适用","display":"上市公司"},
  investors=["公共市场"],
  highlights=["美国最大独立居家输液服务商","服务免疫/肿瘤/罕见病等复杂慢病","并购成长路径"],
  signal_strength=0.55,info_score=8,diff_score=3,copy_score=5,
  recommend="信息丰富（上市公司财报+行业媒体），居家输液模式稳健、顺常识，反共识性低。中国居家护理/输液（京东健康上门、民营护理站）有同类但支付以医保/个人为主、上门服务标准化弱——其“药师驱动+冷链药品+居家场景”的运营体系可对标，尤其适合老龄化下居家医疗趋势。"),
"#1159": dict(founded="1999",
  desc_cn="美国养老与医疗服务业运营商（NASDAQ:ENSG），从单一养老院成长为覆盖全美的风险导向护理网络，自管式运营+频繁收购；1999年成立。",
  payor_model="混合（政府Medicare/Medicaid+个人自付；B端机构运营）",
  funding_latest={"round":"上市公司","amount":"不适用","currency":"USD","date":"1999","display":"上市公司(NASDAQ:ENSG)","investors":["公共市场"]},
  funding_total={"amount":"不适用","display":"上市公司"},
  investors=["公共市场"],
  highlights=["美国养老与医疗运营网络(NASDAQ:ENSG)","自管式运营+频繁收购扩张","风险导向护理模式"],
  signal_strength=0.55,info_score=8,diff_score=4,copy_score=6,
  recommend="信息丰富（上市公司财报+收购报道），自管式运营+并购扩张的成长路径清晰非反共识。中国连锁养老/护理运营（泰康、九如城）可对标其“自营+收购”规模化与风险导向护理——看美国成熟运营商如何用并购把区域小机构整合成网络，对国内整合期有参考。"),
"#1160": dict(founded="1991",
  desc_cn="专注医疗地产（含养老/护理）的REIT（纽交所NHI），以 Triple-net 净租赁向运营商提供资本；1991年成立。",
  payor_model="B端机构付费（Triple-net净租赁，运营商付租金；终端来自政府Medicare/Medicaid+个人自付）",
  funding_latest={"round":"上市公司","amount":"不适用","currency":"USD","date":"1991","display":"上市公司(纽交所NHI)","investors":["公共市场"]},
  funding_total={"amount":"不适用","display":"上市公司"},
  investors=["公共市场"],
  highlights=["医疗地产REIT(纽交所NHI)","Triple-net净租赁资本提供方","稳健收租模式"],
  signal_strength=0.55,info_score=7,diff_score=3,copy_score=5,
  recommend="信息中等（年报+投资者区），纯医疗地产REIT、模式稳健不反共识。与Welltower/Ventas/Ohmega/CareTrust同属“银发地产”资本阵营，单看故事性弱，但作为REIT对照组一员、理解不同杠杆与租户结构差异有用——建议与另四家合并成“美国养老REIT图谱”主题。"),
"#1171": dict(founded="2017",
  desc_cn="长寿科技(抗衰老药物)公司，专注延缓衰老相关疾病的口服小分子药物；2024-09纳斯达克IPO募资1.98亿美元，但上市后股价较发行价暴跌约98%，是生物科技“高预期—破灭”的典型。",
  payor_model="B端机构付费（药企/研发合作）+ 远期上市后为医保/个人支付（尚未商业化）",
  funding_latest={"round":"IPO","amount":"1.98亿美元","currency":"USD","date":"2024-09","display":"纳斯达克IPO募资1.98亿美元 (2024-09)","investors":["NASDAQ公开发行"]},
  funding_total={"amount":"约2.5亿美元","display":"累计约2.5亿美元(含IPO)"},
  investors=["NASDAQ公开发行"],
  highlights=["长寿科技/抗衰老药物研发","2024-09 IPO募资1.98亿美元","上市后股价暴跌约98%"],
  signal_strength=6.55,info_score=8,diff_score=7,copy_score=4,
  recommend="信息丰富（IPO+后续暴跌被广泛报道），是“高预期—破灭”的反共识样本：抗衰老叙事吸金、但临床与商业化存疑、股价暴跌约98%。中国长寿科技/衰老干预赛道刚起步（如衰老时钟公司），可借鉴其“叙事融资”与“临床兑现”的落差教训——对国内创业者是避坑+叙事框架的双重教材。"),
}

def rv(u):
    s=u["signal_strength"];i=u["info_score"];d=u["diff_score"];c=u["copy_score"]
    return round((s*0.3+i*0.3+d*0.2+c*0.2)*10)

UPKEYS=["founded","desc_cn","payor_model","funding_latest","funding_total","investors",
         "highlights","signal_strength","info_score","diff_score","copy_score",
         "research_value","value_score","recommend","update_time"]

changed=[]
for serial,u in U.items():
    e=by.get(serial)
    if not e:
        print("MISSING",serial); continue
    rvv=rv(u)
    u["research_value"]=rvv
    u["value_score"]=rvv   # 旧前端回退兼容
    u["update_time"]="2026-07-16"
    for k in UPKEYS:
        if k in ("research_value","value_score","update_time"): continue
        old=e.get(k)
        e[k]=u[k]
        changed.append((serial,k,old,u[k]))
    e["research_value"]=rvv
    e["value_score"]=rvv
    e["update_time"]="2026-07-16"

json.dump(data,open(PATH,"w",encoding="utf-8"),ensure_ascii=False,indent=1)
print("WROTE all_enterprises.json. updated enterprises:",len(U))
print("research_value sample:")
for s in U:
    print(f"  {s} research_value={by[s]['research_value']} (sig={U[s]['signal_strength']} info={U[s]['info_score']} diff={U[s]['diff_score']} copy={U[s]['copy_score']})")
